apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-repo
spec:
  params:
  - name: revision
    type: string
    default: buil-tekton
  - name: GIT_URL
    type: string
    default: "https://github.com/ketank-new/sacremoses-feedstock.git"
  resources:
    inputs:
    - name: source
      type: git
  steps:
    - name: view-repo
      image: ubuntu
      script: |
        apt-get update
        apt-get install -y wget
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -P /workspace/ 
        bash /workspace/Miniconda3-latest-Linux-x86_64.sh -b -p /workspace/miniconda/
        export PATH=/workspace/miniconda/bin:$PATH
        conda install -y conda-build
        conda build /workspace/source/recipe/meta.yaml