apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-repo
spec:
  params:
  - name: revision
    type: string
    default: buil-tekton
  - name: GIT_URL
    type: string
    default: "https://github.com/ketank-new/sacremoses-feedstock.git"
  resources:
    inputs:
    - name: source
      type: git
  steps:
    - name: view-repo
      image: ubuntu
      scripts: |
        apt-get update
        apt-get install -y anaconda
        sh /workspace/source/.scripts/build_steps.sh